In [22]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.ticker as ticker
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix
import random
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot

#podzielenie bazy na zbór treningowy i testowy
df = pd.read_csv('Data/wine.csv')
df.head()

y=df.iloc[:, 11]
X=df.iloc[:, :-1]
X_train ,X_test ,y_train , y_test=train_test_split(X, y, test_size=0.2)
X_train.head()
X_train.shape
X_test.head()
X_test.shape
print ('Zestaw treningowy:', X_train.shape,  y_train.shape)
print()
print ('Zestaw testowy:', X_test.shape,  y_test.shape)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - k Najbliższych sąsiadów (dla wybranego k) gdzie k = 6
print("Wyniki dla k równego 6")
print()
k_6 = 6
#Train Model and Predict  
neigh6 = KNeighborsClassifier(n_neighbors = k_6).fit(X_train,y_train)
yhat6 = neigh6.predict(X_test)
print("Dokładność zestawu treningowego: %.2f %%" %(100*metrics.accuracy_score(y_train, neigh6.predict(X_train))))
print()
accuracy_KN6 = 100*metrics.accuracy_score(y_test, yhat6)
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_KN6))
print()
r6 = confusion_matrix(y_test, yhat6)
print("Macierz błędu dla k=6\n", r6)
print()
result6 = classification_report(y_test, yhat6)
print("Raport klasyfikacyjny dla k=6\n", result6)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - k Najbliższych sąsiadów (dla wybranego k) gdzie k = 5
print("Wyniki dla k równego 5")
print()
k_5 = 5
#Train Model and Predict  
neigh_5 = KNeighborsClassifier(n_neighbors = k_5).fit(X_train,y_train)
yhat_5 = neigh_5.predict(X_test)
print()
print("Dokładność zestawu treningowego: %.2f %%" %(100*metrics.accuracy_score(y_train, neigh_5.predict(X_train))))
print()
accuracy_KN5 = 100*metrics.accuracy_score(y_test, yhat_5)
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_KN5))
print()
r5 = confusion_matrix(y_test, yhat_5)
print("Macierz błędu dla k=5\n", r5)
print()
result5 = classification_report(y_test, yhat_5)
print("Raport klasyfikacyjny dla k=5\n", result5)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - k Najbliższych sąsiadów (dla wybranego k) gdzie k = 2
print("Wyniki dla k równego 2")
print()
k_2 = 2
#Train Model and Predict  
neigh_2 = KNeighborsClassifier(n_neighbors = k_2).fit(X_train,y_train)
yhat_2 = neigh_2.predict(X_test)
print("Dokładność zestawu treningowego: %.2f %%" %(100*metrics.accuracy_score(y_train, neigh_2.predict(X_train))))
print()
accuracy_KN2 = 100*metrics.accuracy_score(y_test, yhat_2)
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_KN2))
print()
r2 = confusion_matrix(y_test, yhat_2)
print("Macierz błędu dla k=2\n", r2)
print()
result2 = classification_report(y_test, yhat_2)
print("Raport klasyfikacyjny dla k=2\n", result2)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - k Najbliższych sąsiadów (dla wybranego k) gdzie k = 1
print("Wyniki dla k równego 1")
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
k_1 = 1
#Train Model and Predict  
neigh_1 = KNeighborsClassifier(n_neighbors = k_1).fit(X_train,y_train)
yhat_1 = neigh_1.predict(X_test)
print("Dokładność zestawu treningowego: %.2f %%" %(100*metrics.accuracy_score(y_train, neigh_1.predict(X_train))))
print()
accuracy_KN1 = 100*metrics.accuracy_score(y_test, yhat_1)
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_KN1))
print()
r1 = confusion_matrix(y_test, yhat_1)
print("Macierz błędu dla k=1\n", r1)
print()
result1 = classification_report(y_test, yhat_1)
print("Raport klasyfikacyjny dla k=1\n", result1)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - Naive Bayes
print("Naive Bayes")
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
model = GaussianNB()
model.fit(X_train,y_train)
y_pred_GB = model.predict(X_test)
accuracy_GB = metrics.accuracy_score(y_test, y_pred_GB)*100
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_GB))
print()
r_GB = confusion_matrix(y_test, y_pred_GB)
print("Macierz błędu dla Naive Bayes\n", r_GB)
print()
result_GB = classification_report(y_test, y_pred_GB)
print("Raport klasyfikacyjny dla Naive Bayes\n", result_GB)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - drzewa decyzyjne
print("Drzewa decyzyjne")
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred_DR = classifier.predict(X_test)
accuracy_DR = metrics.accuracy_score(y_test, y_pred_DR)*100
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_DR))
print()
r_DR = confusion_matrix(y_test, y_pred_DR)
print("Macierz błędu dla Drzewa decyzyjnych\n", r_DR)
print()
result_DR = classification_report(y_test, y_pred_DR)
print("Raport klasyfikacyjny dla Drzewa decyzyjnych\n", result_DR)
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
#klasyfikator - sieci neuronowe
print("Sieci neuronowe")
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
random.seed(42)
rf = RandomForestRegressor(n_estimators=10)
rf.fit(X_train, y_train)
model_SN = Sequential()
model_SN.add(Dense(2000, input_dim=11, activation= "relu"))
model_SN.add(Dense(100, activation= "relu"))
model_SN.add(Dense(1))
model_SN.summary() #Print model Summary
# Compile model
model_SN.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
# Fit Model
model_SN.fit(X_train, y_train, epochs=10)
pred_SN=rf.predict(X_test)
score_SN = np.sqrt(mean_squared_error(y_test,pred_SN))
print(100*score_SN)
# Evaluation while fitting the model
model_SN.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))
pred_SN= model_SN.predict(X_test)
score_SN = np.sqrt(mean_squared_error(y_test,pred_SN))
sc_SN = score_SN*100
print(sc_SN)

#Prediction using Random Forest 
y_test_rf = rf.predict(X_test)
#Prediction using Neural Network
y_test_nn = model.predict(X_test)
#Random forest
print("Random forest")
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
clf=RandomForestClassifier(n_estimators=100)
#making 100 decision trees from our data d1
clf.fit(X_train,y_train)
#training our machine by providing x inputs and providing answers/targets as y_train
y_pred_Random=clf.predict(X_test)
#calculating output of data not given to machine as Training data to check if our model works
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
accuracy_RandomF = metrics.accuracy_score(y_test, y_pred_Random)*100
print("Dokładność zestawu testowego:", accuracy_RandomF)
print()
r_Random = confusion_matrix(y_test, y_pred_Random)
print("Macierz błędu dla Random forest\n", r_Random)
print()
result_Random = classification_report(y_test, y_pred_Random)
print("Raport klasyfikacyjny dla Random forest\n", result_Random)
print()
#Support Vector Machines
print("Support Vector Machines")
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
y_pred_SVM = svclassifier.predict(X_test)
accuracy_SVM = metrics.accuracy_score(y_test, y_pred_SVM)*100
print("Dokładność zestawu testowego: %.2f %%" %(accuracy_SVM))
print()
print("Macierz błędu dla Support Vector Machines\n",confusion_matrix(y_test,y_pred_SVM))
print()
print("Raport klasyfikacyjny dla Support Vector Machines\n", classification_report(y_test,y_pred_SVM))
print()
print("------------------------------------------------------------------------------------------------------------------------------------------------------")
print("Porównywanie klasyfikatorów")
print()
data = [go.Bar(
            x=["k = 6", "k = 5", "k = 2", "k = 1", "Naive Bayes", "Drzewa decyzyjne", "Sieci neuronowe", "Random Forest", "Support Vector Machines"],
            y=[accuracy_KN6, accuracy_KN5, accuracy_KN2, accuracy_KN1, accuracy_GB, accuracy_DR, sc_SN, accuracy_RandomF, accuracy_SVM],
            marker=dict(color='rgb(158,202,225)',
            line=dict(color='rgba(254, 69, 62, 1)',
            width=1.5),
        ),
    opacity=0.6
    )]

iplot(data, filename='text-hover-bar')

Zestaw treningowy: (1279, 11) (1279,)

Zestaw testowy: (320, 11) (320,)

------------------------------------------------------------------------------------------------------------------------------------------------------
Wyniki dla k równego 6

Dokładność zestawu treningowego: 63.33 %

Dokładność zestawu testowego: 49.06 %

Macierz błędu dla k=6
 [[  0   0   1   0   1   0]
 [  0   0   8   2   1   0]
 [  0   0 100  35   1   0]
 [  0   2  62  50  11   0]
 [  0   1  13  23   7   0]
 [  0   0   1   0   1   0]]

Raport klasyfikacyjny dla k=6
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.54      0.74      0.62       136
           6       0.45      0.40      0.43       125
           7       0.32      0.16      0.21        44
           8       0.00      0.00      0.00         2

    accuracy                           0.49       320
   macro avg       